default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: shaftsealkit_dev

test:
  <<: *default
  database: shaftsealkit_test

production:
  <<: *default
  host: localhost
  port: 5432
  database: shaftsealkit_prod
  username: deploy
  password: yourpasswordhere